[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

  Content-Security-Policy = "default-src https://cdn.cloudflare.net https://ajax.cloudflare.com ; child-src 'none'; object-src 'none'; frame-ancestors 'none'; report-uri 'music.report-uri.com/r/d/csp/reportOnly';"
