[[headers]]
  for = "/*"
  [headers.values]
  Content-Secuirty-Policy: frame-ancestors 'none'
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    #  Multi-key header rules are expressed with multi-line strings
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
