[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "script-src 'strict-dynamic' 'nonce-rAnd0m123' 'unsafe-inline' http: https:;
    object-src 'none';
    base-uri 'none';
    report-uri https://music.repot-uri.com/r/d/csp/reportOnly;"

